// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/patients/{id}": {
            "get": {
                "description": "Get a patient's details by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get patient by ID",
                "operationId": "get-patient-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Patient"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/records": {
            "post": {
                "description": "Add a new record for a patient.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Add a new record",
                "operationId": "add-record",
                "parameters": [
                    {
                        "description": "Record",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Record"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Record"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Search patient records by patient ID or hospital.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search patient records",
                "operationId": "search-patient-records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient ID",
                        "name": "patientId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Hospital",
                        "name": "hospital",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Record"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DiagnosticRecord": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "diagnosis": {
                    "type": "string"
                },
                "hospital": {
                    "type": "string"
                },
                "specialist": {
                    "type": "string"
                }
            }
        },
        "main.Patient": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.Record": {
            "type": "object",
            "properties": {
                "diagnosticRecords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.DiagnosticRecord"
                    }
                },
                "patient": {
                    "$ref": "#/definitions/main.Patient"
                },
                "treatmentRecords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.TreatmentRecord"
                    }
                },
                "visitRecords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.VisitRecord"
                    }
                }
            }
        },
        "main.TreatmentRecord": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "hospital": {
                    "type": "string"
                },
                "outcome": {
                    "type": "string"
                },
                "treatment": {
                    "type": "string"
                }
            }
        },
        "main.VisitRecord": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "doctorName": {
                    "type": "string"
                },
                "hospital": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Medical Records API",
	Description:      "This is a sample server for managing medical records.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
